version: "3.8"

services:
  db-remote:
    image: postgres:14.5
    ports:
      - 5433:5432
    container_name: "db-remote"
    networks:
      db-network:
        ipv4_address: 172.28.0.3
    env_file: "./remote.env"
    volumes:
      - ./remote-db-data:/var/lib/postgresql/data
      - ./remote-db-repl:/var/lib/postgresql/repl
      - ./remote.pg_hba.conf:/etc/postgresql/pg_hba.conf
      - ./remote.postgresql.conf:/etc/postgresql/postgresql.conf
      - ./scripts/init.sh:/docker-entrypoint-initdb.d/init.sh
      - ./.pgpass:/var/lib/postgresql/.pgpass
    command: postgres -c config_file=/etc/postgresql/postgresql.conf -c hba_file=/etc/postgresql/pg_hba.conf
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    restart: always

networks:
  db-network: 
    driver: bridge
    name: db-network
    ipam:
      config:
        - subnet: 172.28.0.0/16
          gateway: 172.28.0.1